const tintColor = '#9d2222';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  navRed:'#fff',
  calendarRedText:'#F20909',
  tabRedColor:'#e60c0c',
  navColor:'#f20909',
  grayTextColor:'#555555',
  thingrayTextColor:'#6E6E6E',
  lightGrayTextColor:'#bdbdbd',
  redTextColor:'#e60c0c',
  lightredTextColor:'#f20909',
  greenTextColor:'#60BE98',
  blueTextColor:'#0d47a1',
  lightblue:'#C8E7EA',
  yellowTextColor:'#f28500',
  backgroundcolor:'#FAFAFA',
  midnightblue:'#189AA8',
  burlywood:'#DBEEE6',
  lightred:'#D32F2F',
  pink:'#F2D1D1',
  calendarLocationBoxColor:'#eeeeee',
  calendarLocationBorderBoxColor:'#e0e0e0',
  calendarYellowDotColor:'#f28500',
  calendarRedDotColor:'#f20909',
  calendarBlueDotColor:'#0d47a1',
  calendarBlueText:'#0d47a1',
  calendarRedText:'#f20909',
  calendarGrayText:'#fafafa',
  calendarGrayBackgroundColor:'#fafafa',

  // 
  grayText:'#555555',
  lightgrayText:'#9E9E9E',

  grayColor:'#bdbdbd',
  redColor:'#f20909',
  //
  leaveCircleRed:'#D32F2F',
  leaveCircleGreen:'#60BE98',
  leaveCircleBlue:'#189AA8'
};
