export default {
  ALERT_CANNOT_CONNECT_TITLE: 'Cannot connect to server. Please contact system administrator.',
  ALERT_CANNOT_CONNECT_DESC: '',
  ALERT_CANNOT_CONNECT_BUTTON: 'OK',

  ALERT_NONPAYROLL_NODATA_TITLE: 'No Data.',
  ALERT_NONPAYROLL_NODATA_BUTTON: 'OK',

  ALERT_AUTHORLIZE_ERROR_TITLE: 'Error',
  ALERT_AUTHORLIZE_ERROR_MESSAGE: 'Have login from another device',


  CALENDAR_DOWNLOAD_PDF_SUCCESS_TITLE: 'Success',
  CALENDAR_DOWNLOAD_PDF_SUCCESS_DESC: ' has been download',

  CALENDER_YEARVIEW_YEAR_TODAY_BUTTON: "TODAY",

  CALENDER_YEARVIEW_SELECT_YEAR_TITLE: "Select year",
  CALENDER_YEARVIEW_SELECT_YEAR_BUTTON: "OK",

  CALENDER_YEARVIEW_DOWNLOAD_PDF_TITLE: "Select year you want to download.",
  CALENDER_YEARVIEW_DOWNLOAD_PDF_BUTTON: "Download",

  CALENDER_YEARVIEW_LOCATION_TITLE: "Select location.",
  CALENDER_YEARVIEW_ALERT_LOCATION_BUTTON: "OK",

  CALENDER_YEARVIEW_SYNC_CALENDAR_TITLE: "Sync Calendar.",
  CALENDER_YEARVIEW_SYNC_CALENDAR_BUTTON: 'Do you want to sync Calendar to your device?',

  CALENDAR_ALERT_SYNC_CALENDAR_TITLE_SUCCESS: 'Success.',
  CALENDAR_ALERT_SYNC_CALENDAR_DESC_SUCCESS: 'Sync calendar',
  CALENDAR_ALERT_SYNC_CALENDAR_BUTTON_SUCCESS: 'OK',


  CALENDAR_ALERT_PDF_TITLE_SUCCESS: 'Success.',

  CALENDAR_ALERT_PDF_DESC_SUCCESS_1: 'Calendar ',
  CALENDAR_ALERT_PDF_DESC_SUCCESS_2: ' has been downloaded.',

  CALENDAR_ALERT_PDF_TITLE_FAIL: 'Calendar ',
  CALENDAR_ALERT_PDF_DESC_FAIL: 'No data',

  CALENDAR_ALERT_PDF_BUTTON_SUCCESS: 'OK',


  CALENDAR_MONTHVIEW_EVENT_TITLE: 'Event',
  CALENDAR_MONTHVIEW_NO_EVENT_TEXT: 'No event',

  CALENDAR_MONTHVIEW_SELECT_NEW_PLACE_TITLE: 'Sorry',
  CALENDAR_MONTHVIEW_SELECT_NEW_PLACE_DESC: 'No Data',
  // 
  REGISTER_INVALID_TITLE: 'Sorry',
  REGISTER_INVALID_DESC: 'Invalid User ID or Password.',

  SERVER_ERROR_TITLE: 'MHF00002ACRI',
  SERVER_ERROR_DESC: 'System Error (API). Please contact system administrator.',

  REGISTER_PIN_ERROR_TITLE: 'Sorry',
  REGISTER_PIN_ERROR_DESC: 'Confirm PIN incorrect.Please try again.',

  ALERT_PIN_TITLE_NOT_CORRECT: 'Sorry',
  ALERT_PIN_DESC_NOT_CORRECT: 'Incorrect PIN.Please try again.',
  ALERT_PIN_DESC_TOO_MANY_NOT_CORRECT: 'Too many attempts.Please Login again.',

  ALERT_RESET_PIN_TITLE: 'Reset PIN',
  ALERT_RESET_PIN_DESC: 'Do you want to reset the PIN? ',

  ALERT_CANNOT_DELETE_PIN_TITLE: 'Reset PIN',
  ALERT_CANNOT_DELETE_PIN_DESC: 'Cannot reset PIN,Please contact system administrator.',

  CHANGE_PIN_ENTER_CURRENT_PIN_TITLE: 'Enter Current PIN',
  CHANGE_PIN_ENTER_NEW_PIN_1_TITLE: 'Enter New PIN',
  CHANGE_PIN_ENTER_NEW_PIN_2_TITLE: 'Confirm New PIN',

  CHANGE_PIN_SUCCESS_TITLE: 'Change PIN Success',

  CHANGE_PIN_FAIL_TITLE: 'Sorry',
  CHANGE_PIN_FAIL_DESC: 'Current PIN incorrect.Please try again',

  CHANGE_PIN_NOT_MATCH_TITLE: 'Sorry',
  CHANGE_PIN_NOT_MATCH_DESC: ' PIN incorrect.Please try again',

  ALERT_PAYSLIP_CANNOT_DOWNLOAD_TITLE: 'Sorry',
  ALERT_PAYSLIP_CANNOT_DOWNLOAD_DESC: 'Cannot download file.',


};
