export default {
  ALERT_CANNOT_CONNECT_TITLE: 'Cannot connect to server. Please contact system administrator.',
  ALERT_CANNOT_CONNECT_DESC: '',
  ALERT_CANNOT_CONNECT_BUTTON: 'OK',


  ALERT_NONPAYROLL_NODATA_TITLE: 'No Data.',
  ALERT_NONPAYROLL_NODATA_BUTTON: 'OK',


  CALENDAR_DOWNLOAD_PDF_SUCCESS_TITLE: 'Success',
  CALENDAR_DOWNLOAD_PDF_SUCCESS_DESC: ' has been download',

  CALENDER_YEARVIEW_YEAR_TODAY_BUTTON: "TODAY",

  CALENDER_YEARVIEW_SELECT_YEAR_TITLE: "Select year",
  CALENDER_YEARVIEW_SELECT_YEAR_BUTTON: "OK",

  CALENDER_YEARVIEW_DOWNLOAD_PDF_TITLE: "Select year you want to download.",
  CALENDER_YEARVIEW_DOWNLOAD_PDF_BUTTON: "Download",

  CALENDER_YEARVIEW_LOCATION_TITLE: "Select location.",
  CALENDER_YEARVIEW_ALERT_LOCATION_BUTTON: "OK",

  CALENDER_YEARVIEW_SYNC_CALENDAR_TITLE: "Sync Calendar.",
  CALENDER_YEARVIEW_SYNC_CALENDAR_BUTTON: 'Do you want to sync Calendar to your device?',

  CALENDAR_ALERT_SYNC_CALENDAR_TITLE_SUCCESS: 'Success.',
  CALENDAR_ALERT_SYNC_CALENDAR_DESC_SUCCESS: 'Sync calendar',
  CALENDAR_ALERT_SYNC_CALENDAR_BUTTON_SUCCESS: 'OK',

  CALENDAR_MONTHVIEW_EVENT_TITLE: 'Event',
  CALENDAR_MONTHVIEW_NO_EVENT_TEXT: 'No event',

  SERVER_ERROR_TITLE: 'MHF00002ACRI',
  SERVER_ERROR_DESC: 'System Error (API). Please contact system administrator.',

  REGISTER_PIN_ERROR_TITLE: 'Sorry',
  REGISTER_PIN_ERROR_DESC: 'Confirm PIN incorrect.Please try again.',

  ALERT_PIN_TITLE_NOT_CORRECT: 'Sorry',
  ALERT_PIN_DESC_NOT_CORRECT: 'Incorrect PIN.Please try again.',
  ALERT_PIN_DESC_TOO_MANY_NOT_CORRECT: 'Too many attempts.Please Login again.',

  ALERT_RESET_PIN_TITLE: 'Reset PIN',
  ALERT_RESET_PIN_DESC: 'Do you want to reset the PIN? '


};
